### ISSUE TITLE
iPhone 7 problem

### ISSUE THREAD

**Issue by AlexGsmAudit** [0x7ff/gaster#12]
Please, check iPhone 7

Product type: iPhone9,1
Chip ID: 0x8010
Board ID: 0x08

When I do "gaster pwn", the device does not start after I upload all the files: ibec, ibss, devicetree, kernel.
For example when I do pwn mode through "ipwndfu -p && ipwndfu --patch" and upload the same files then the device starts correctly.

**Comment by P5-2005** [comment]
> Please, check iPhone 7
> 
> Product type: iPhone9,1 Chip ID: 0x8010 Board ID: 0x08
> 
> When I do "gaster pwn", the device does not start after I upload all the files: ibec, ibss, devicetree, kernel. For example when I do pwn mode through "ipwndfu -p && ipwndfu --patch" and upload the same files then the device starts correctly.

not gaster issue,
comparing with ipwndfu not helpful for your issue with loading patched bootchain on device, from my end tried : 9,1/9,2/9,3/9,4 only pwn with gaster and all fine and first try
so not gaster issue 100%
