### ISSUE TITLE
Unable to activate device when using gaster to tether boot.

### ISSUE THREAD

**Issue by galaxy4627** [0x7ff/gaster#13]
I have been using Gaster to tether boot into iOS 14 and for some reason I get this issue, 
![413B8E4A-3967-4366-9128-144541B608D0](https://user-images.githubusercontent.com/100154768/177046895-2a3bb191-66bc-4d1b-b0cc-92b05f9febcd.jpeg)
the thing is using ipwnder_lite or ipwndfu with linus sigchecks remover it activates just fine.

**Comment by Thekidiacs** [comment]
I get this issue when I run ipwndfu. I don't think this is a gaster issue. I downgraded from 15.5 to 14.2 and I get the same exact issue that your getting. What are the commands that you used for ipwnder_lite to get it to boot? I know you said that ipwnder_lite also works so I just want to know what commands you used to get it to boot. I know the last command is ./boot.sh but what should I do before that so it works with ipwnder_lite.

**Comment by piaomiaoguhong10** [comment]
I'm facing this error, too. Do you find any solution?

**Comment by ifpdz** [comment]
I am getting the same issue here, hope will be fixed asap. @0x7ff

**Comment by P5-2005** [comment]
> I have been using Gaster to tether boot into iOS 14 and for some reason I get this issue, ![413B8E4A-3967-4366-9128-144541B608D0](https://user-images.githubusercontent.com/100154768/177046895-2a3bb191-66bc-4d1b-b0cc-92b05f9febcd.jpeg) the thing is using ipwnder_lite or ipwndfu with linus sigchecks remover it activates just fine.

seem last commit : revert; fix this issue, can you retry?

**Comment by galaxy4627** [comment]
> > I have been using Gaster to tether boot into iOS 14 and for some reason I get this issue, ![413B8E4A-3967-4366-9128-144541B608D0](https://user-images.githubusercontent.com/100154768/177046895-2a3bb191-66bc-4d1b-b0cc-92b05f9febcd.jpeg) the thing is using ipwnder_lite or ipwndfu with linus sigchecks remover it activates just fine.
> 
> seem last commit : revert; fix this issue, can you retry?

yeah last time I used gaster it worked so
