### ISSUE TITLE
gaster pwn keeps stucking

### ISSUE THREAD

**Issue by meichengg** [0x7ff/gaster#15]
Hi, the process of `gaster pwn` didn't give me any result but stucking at this step. I had my iPhone X booted in DFU mode already. Please help 🙏🏻 

![image](https://user-images.githubusercontent.com/25204246/182073463-e8f13007-288a-4f1e-87ef-1039ffcd341e.png)

**Comment by P5-2005** [comment]
try this : 
killall -STOP AMPDevicesAgent AMPDeviceDiscoveryAgent MobileDeviceUpdater

then try again to pwn, is this real mac or hackintosh?

**Comment by meichengg** [comment]
> try this : killall -STOP AMPDevicesAgent AMPDeviceDiscoveryAgent MobileDeviceUpdater
> 
> then try again to pwn, is this real mac or hackintosh?

im using hackintosh

**Comment by meichengg** [comment]
> killall -STOP AMPDevicesAgent AMPDeviceDiscoveryAgent MobileDeviceUpdater

it's not working either 🤷🏻

**Comment by P5-2005** [comment]
> > try this : killall -STOP AMPDevicesAgent AMPDeviceDiscoveryAgent MobileDeviceUpdater
> > then try again to pwn, is this real mac or hackintosh?
> 
> im using hackintosh

your cpu is intel or amd?

**Comment by meichengg** [comment]
> > > try this : killall -STOP AMPDevicesAgent AMPDeviceDiscoveryAgent MobileDeviceUpdater
> > > then try again to pwn, is this real mac or hackintosh?
> > 
> > 
> > im using hackintosh
> 
> your cpu is intel or amd?

intel

**Comment by otavioses** [comment]
Same error here. I have tried in an intel hackintosh and real Mac

**Comment by J1NNX26** [comment]
Same here, I'm stuck too !! Did anybody find a solution to this? Im trying on my iPhone 7 on Mac with Intel chip.

**Comment by P5-2005** [comment]
macbook air 2018 t2, macos bigsur, all fine, both build iokit/libusb, many devices : iphone8,7+,X, 6s, SE1, Ipad mini 4
all success and first try no issue

**Comment by CDSQ** [comment]
don't use Type-C, if only Type-C Port you Can use USB-CtoUSB-A HUB，Don't use single Type-C to USB-A Converter！
