### ISSUE TITLE
Device does not accept images after successfull patching

### ISSUE THREAD

**Issue by danio0701** [0x7ff/gaster#16]
The device does not accept ibss, ibec etc to enter purple mode when the device is patched with this pwnd. While using different pwnd all works fine. 

Question: How to fix my files to let it works with this pwnd?

Many thanks

**Comment by P5-2005** [comment]
there is new version of magiccfg working with gaster and purplemode, if you need to know how to fix your files ask the dev of magiccfg he already did with gaster

**Comment by danio0701** [comment]
> there is new version of magiccfg working with gaster and purplemode, if you need to know how to fix your files ask the dev of magiccfg he already did with gaster

I asked already but I did not get an answer :P Maybe in the future, he will post a guide but he is not sure yet. For now, he don't share.
