### ISSUE TITLE
can't send iboot even success on ipwndfu

### ISSUE THREAD

**Issue by xgrinda** [0x7ff/gaster#3]
any idea why can't send iboot patched .... itry ipwndfu with rmsgcheck mbut on gaster didn't success ?

::  USB_SERIAL_NUMBER: CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:FFFFFFFFFFFFF IBFL:3C SRNM:[FFFFFFFFFFFFF]
::
=======================================

Boot Failure Count: 4  Panic Fail Count: 0
Delaying boot for 0 seconds. Hit enter to break into the command prompt...
boot-command 'fsboot' not supported
Entering recovery mode, starting command prompt
] USB command: "go"
Memory image not valid

**Comment by 0x7ff** [comment]
Hey @xgrinda,
The patches should be applied to all boot chain components because these patches aren't persistent (it just patches the digest check in the IMG4 parser) but I'm gonna add support for iBSS/iBEC patching and booting soon.

**Comment by xgrinda** [comment]
Thanks for your response, it's powerful, good luck with that 👍
