### ISSUE TITLE
8955 - 8960 Unknown USB descriptor 

### ISSUE THREAD

**Issue by amats211** [0x7ff/gaster#30]
8955 and 8960 shows unknown USB descriptor in windows after PATCH

![image](https://user-images.githubusercontent.com/4814098/195083503-44fbbaa3-dceb-4a34-8280-c1398c115a53.png)

**Comment by P5-2005** [comment]
i confirm, same issue from my end even on last commit, on A7 device stay on black screen and got unknow usb, on A6 device panic then reboot to normal mode

**Comment by plooshi** [comment]
![image](https://user-images.githubusercontent.com/56302322/195994032-0a20c3e4-5370-46a2-9a95-630464e257fa.png)
i can also confirm. (libusbk 5s)

**Comment by plooshi** [comment]
@0x7ff this still exists on 7ffffffeb14dab3ff1d7f4335bed25140f0e098b, please help us windows A7 and A6X users :D

**Comment by plooshi** [comment]
also not patched with #32

**Comment by plooshi** [comment]
latest commit may or may not fix A6X (i dont know as i dont have one) and 100% not A7.

**Comment by amats211** [comment]
tried with latest commit but still same, now is just stucked on PATCH and does not continue..

**Comment by plooshi** [comment]
This also is broken on Linux, PATCHing indefinitely on A7. A6X I don't know as I don't have one.

**Comment by plooshi** [comment]
> This also is broken on Linux, PATCHing indefinitely on A7. A6X I don't now as I don't have one.

haven't tested any of the latest commits for this.

**Comment by Stokes83** [comment]
i have a problem on ipad6,4 (iPad Pro 9,7)

**Comment by plooshi** [comment]
> i have a problem on ipad6,4 (iPad Pro 9,7)

That's A9X, make a new issue.

**Comment by ploosh-alt** [comment]
@0x7ff any way to fix this?

**Comment by plooshi** [comment]
![image](https://user-images.githubusercontent.com/56302322/196284731-4b4568fd-da9d-455a-bb8b-3a8131a45459.png)
still broke on latest commit

**Comment by plooshi** [comment]
dont mind me having a ton of binaries

**Comment by ploosh-alt** [comment]
any update?

**Comment by 0x7ff** [comment]
This issue exists within the spray stage as it uses large leak method on these devices and it sometimes sends the USB packet without the header so nothing was sent to the device and we can use a different driver to fix this issue like iRemoval Pro which uses the UsbDk driver or by adding USBPcap support in gaster to reliably detect the unsent packets.

**Comment by plooshi** [comment]
@0x7ff hmm, alright. i dont really know libusb so i cant really craft a pr.

**Comment by plooshi** [comment]
libusbK, dont know how to install UsbDk
![image](https://user-images.githubusercontent.com/56302322/197581340-82eeb249-9906-4cc8-99a7-583a8ef19719.png)

**Comment by P5-2005** [comment]
> libusbK, dont know how to install UsbDk ![image](https://user-images.githubusercontent.com/56302322/197581340-82eeb249-9906-4cc8-99a7-583a8ef19719.png)

https://github.com/daynix/UsbDk/releases

**Comment by plooshi** [comment]
Alright, now with UsbDk, it patches forever, like Linux does.

**Comment by P5-2005** [comment]
> Alright, now with UsbDk, it patches forever, like Linux does.

you must restart first after install of usdbk pcap, also you should check if the value of usdbk upperfilter is added on the reg like this :  

![usbdkmsi](https://user-images.githubusercontent.com/36075275/197584133-465db331-9988-4f8b-bb0b-8ca5d44397f7.png)

**Comment by plooshi** [comment]
> you must restart first after install of usdbk pcap

i rebooted, and the value of the upperfilter is correct. im on A7 iPhone6,1 (5s gsm)

**Comment by P5-2005** [comment]
> > you must restart first after install of usdbk pcap
> 
> i rebooted, and the value of the upperfilter is correct. im on A7 iPhone6,1 (5s gsm)

if you run this on cmd : set LIBUSB_DEBUG=4 then run gaster pwn what you get? im afraid need libusb dll debug version for that(this from last year i dont remember in detail)

**Comment by plooshi** [comment]
looks like it still needs libusbk installed to find the handle

**Comment by P5-2005** [comment]
> looks like it still needs libusbk installed to find the handle

what driver you are using on dfu mode if not signed libusbk one from zadiag?

**Comment by plooshi** [comment]
@P5-2005 its libusbk from zadig, yes

**Comment by plooshi** [comment]
[gaster_debug.log](https://github.com/0x7ff/gaster/files/9854025/gaster_debug.log)
@P5-2005 heres the debug log... its massive.

**Comment by P5-2005** [comment]
> [gaster_debug.log](https://github.com/0x7ff/gaster/files/9854025/gaster_debug.log) @P5-2005 heres the debug log... its massive.

your setup is fine now, messing gaster use usbdk like backend for A6/A7, 7000 request then cancel in the middle to return 64  on libusb only usbdk can handle it on windows, idk if gaster dev can look at usbdkhelperdll can be used instead of libusb on A6/A7 only
this objdump from usbdkhelper :
```
[Ordinal/Name Pointer] Table
        [   0] UsbDk_AbortPipe
        [   1] UsbDk_AddExtendedHideRule
        [   2] UsbDk_AddExtendedPersistentHideRule
        [   3] UsbDk_AddHideRule
        [   4] UsbDk_AddPersistentHideRule
        [   5] UsbDk_ClearHideRules
        [   6] UsbDk_CloseHiderHandle
        [   7] UsbDk_CreateHiderHandle
        [   8] UsbDk_DeleteAllPersistentRules
        [   9] UsbDk_DeleteExtendedPersistentHideRule
        [  10] UsbDk_DeletePersistentHideRule
        [  11] UsbDk_GetConfigurationDescriptor
        [  12] UsbDk_GetDevicesList
        [  13] UsbDk_GetRedirectorSystemHandle
        [  14] UsbDk_InstallDriver
        [  15] UsbDk_ReadPipe
        [  16] UsbDk_ReleaseConfigurationDescriptor
        [  17] UsbDk_ReleaseDevicesList
        [  18] UsbDk_ResetDevice
        [  19] UsbDk_ResetPipe
        [  20] UsbDk_SetAltsetting
        [  21] UsbDk_StartRedirect
        [  22] UsbDk_StopRedirect
        [  23] UsbDk_UninstallDriver
        [  24] UsbDk_WritePipe
```
and here from libusb-1.0.dll
```
[Ordinal/Name Pointer] Table
        [   1] libusb_alloc_streams
        [   0] libusb_alloc_streams
        [   3] libusb_alloc_transfer
        [   2] libusb_alloc_transfer
        [   4] libusb_attach_kernel_driver
        [   5] libusb_attach_kernel_driver
        [   7] libusb_bulk_transfer
        [   6] libusb_bulk_transfer
        [   9] libusb_cancel_transfer
        [   8] libusb_cancel_transfer
        [  10] libusb_claim_interface
        [  11] libusb_claim_interface
        [  13] libusb_clear_halt
        [  12] libusb_clear_halt
        [  15] libusb_close
        [  14] libusb_close
        [  16] libusb_control_transfer
        [  17] libusb_control_transfer
        [  19] libusb_detach_kernel_driver
        [  18] libusb_detach_kernel_driver
        [  21] libusb_dev_mem_alloc
        [  20] libusb_dev_mem_alloc
		[  22] libusb_dev_mem_free
        [  23] libusb_dev_mem_free
        [  25] libusb_error_name
        [  24] libusb_error_name
        [  27] libusb_event_handler_active
        [  26] libusb_event_handler_active
        [  28] libusb_event_handling_ok
        [  29] libusb_event_handling_ok
        [  31] libusb_exit
        [  30] libusb_exit
        [  33] libusb_free_bos_descriptor
        [  32] libusb_free_bos_descriptor
        [  34] libusb_free_config_descriptor
        [  35] libusb_free_config_descriptor
        [  37] libusb_free_container_id_descriptor
        [  36] libusb_free_container_id_descriptor
        [  39] libusb_free_device_list
        [  38] libusb_free_device_list
        [  41] libusb_free_pollfds
        [  40] libusb_free_pollfds
        [  43] libusb_free_ss_endpoint_companion_descriptor
        [  42] libusb_free_ss_endpoint_companion_descriptor
        [  44] libusb_free_ss_usb_device_capability_descriptor
        [  45] libusb_free_ss_usb_device_capability_descriptor
        [  47] libusb_free_streams
        [  46] libusb_free_streams
        [  49] libusb_free_transfer
        [  48] libusb_free_transfer
        [  50] libusb_free_usb_2_0_extension_descriptor
        [  51] libusb_free_usb_2_0_extension_descriptor
        [  53] libusb_get_active_config_descriptor
        [  52] libusb_get_active_config_descriptor
        [  55] libusb_get_bos_descriptor
		[  54] libusb_get_bos_descriptor
        [  56] libusb_get_bus_number
        [  57] libusb_get_bus_number
        [  59] libusb_get_config_descriptor
        [  58] libusb_get_config_descriptor
        [  61] libusb_get_config_descriptor_by_value
        [  60] libusb_get_config_descriptor_by_value
        [  62] libusb_get_configuration
        [  63] libusb_get_configuration
        [  65] libusb_get_container_id_descriptor
        [  64] libusb_get_container_id_descriptor
        [  67] libusb_get_device
        [  66] libusb_get_device
        [  68] libusb_get_device_address
        [  69] libusb_get_device_address
        [  71] libusb_get_device_descriptor
        [  70] libusb_get_device_descriptor
        [  73] libusb_get_device_list
        [  72] libusb_get_device_list
        [  74] libusb_get_device_speed
        [  75] libusb_get_device_speed
        [  77] libusb_get_max_iso_packet_size
        [  76] libusb_get_max_iso_packet_size
        [  79] libusb_get_max_packet_size
		[  78] libusb_get_max_packet_size
        [  80] libusb_get_next_timeout
        [  81] libusb_get_next_timeout
        [  83] libusb_get_parent
        [  82] libusb_get_parent
        [  85] libusb_get_pollfds
        [  84] libusb_get_pollfds
        [  87] libusb_get_port_number
        [  86] libusb_get_port_number
        [  89] libusb_get_port_numbers
        [  88] libusb_get_port_numbers
        [  90] libusb_get_port_path
        [  91] libusb_get_port_path
        [  93] libusb_get_ss_endpoint_companion_descriptor
        [  92] libusb_get_ss_endpoint_companion_descriptor
        [  95] libusb_get_ss_usb_device_capability_descriptor
        [  94] libusb_get_ss_usb_device_capability_descriptor
        [  96] libusb_get_string_descriptor_ascii
        [  97] libusb_get_string_descriptor_ascii
        [  99] libusb_get_usb_2_0_extension_descriptor
        [  98] libusb_get_usb_2_0_extension_descriptor
        [ 101] libusb_get_version
        [ 100] libusb_get_version
        [ 102] libusb_handle_events
        [ 103] libusb_handle_events
        [ 105] libusb_handle_events_completed
        [ 104] libusb_handle_events_completed
        [ 107] libusb_handle_events_locked
        [ 106] libusb_handle_events_locked
        [ 108] libusb_handle_events_timeout
        [ 109] libusb_handle_events_timeout
        [ 111] libusb_handle_events_timeout_completed
        [ 110] libusb_handle_events_timeout_completed
        [ 113] libusb_has_capability
        [ 112] libusb_has_capability
        [ 114] libusb_hotplug_deregister_callback
        [ 115] libusb_hotplug_deregister_callback
        [ 117] libusb_hotplug_get_user_data
        [ 116] libusb_hotplug_get_user_data
        [ 119] libusb_hotplug_register_callback
        [ 118] libusb_hotplug_register_callback
        [ 120] libusb_init
		[ 121] libusb_init
        [ 123] libusb_interrupt_event_handler
        [ 122] libusb_interrupt_event_handler
        [ 125] libusb_interrupt_transfer
        [ 124] libusb_interrupt_transfer
        [ 126] libusb_kernel_driver_active
        [ 127] libusb_kernel_driver_active
        [ 129] libusb_lock_event_waiters
        [ 128] libusb_lock_event_waiters
        [ 131] libusb_lock_events
        [ 130] libusb_lock_events
        [ 133] libusb_open
        [ 132] libusb_open
        [ 135] libusb_open_device_with_vid_pid
        [ 134] libusb_open_device_with_vid_pid
        [ 136] libusb_pollfds_handle_timeouts
        [ 137] libusb_pollfds_handle_timeouts
        [ 139] libusb_ref_device
        [ 138] libusb_ref_device
        [ 141] libusb_release_interface
        [ 140] libusb_release_interface
        [ 142] libusb_reset_device
        [ 143] libusb_reset_device
        [ 145] libusb_set_auto_detach_kernel_driver
        [ 144] libusb_set_auto_detach_kernel_driver
        [ 147] libusb_set_configuration
        [ 146] libusb_set_configuration
        [ 148] libusb_set_debug
        [ 149] libusb_set_debug
        [ 151] libusb_set_interface_alt_setting
        [ 150] libusb_set_interface_alt_setting
        [ 153] libusb_set_log_cb
        [ 152] libusb_set_log_cb
        [ 155] libusb_set_option
        [ 154] libusb_set_option
        [ 157] libusb_set_pollfd_notifiers
		[ 156] libusb_set_pollfd_notifiers
        [ 158] libusb_setlocale
        [ 159] libusb_setlocale
        [ 161] libusb_strerror
        [ 160] libusb_strerror
        [ 163] libusb_submit_transfer
        [ 162] libusb_submit_transfer
        [ 164] libusb_transfer_get_stream_id
        [ 165] libusb_transfer_get_stream_id
        [ 167] libusb_transfer_set_stream_id
        [ 166] libusb_transfer_set_stream_id
        [ 169] libusb_try_lock_events
        [ 168] libusb_try_lock_events
        [ 170] libusb_unlock_event_waiters
        [ 171] libusb_unlock_event_waiters
        [ 173] libusb_unlock_events
        [ 172] libusb_unlock_events
        [ 175] libusb_unref_device
        [ 174] libusb_unref_device
        [ 177] libusb_wait_for_event
        [ 176] libusb_wait_for_event
        [ 179] libusb_wrap_sys_device
        [ 178] libusb_wrap_sys_device
```

**Comment by plooshi** [comment]
@P5-2005 yes, but linux also patches forever... so im guessing thats a different issue

**Comment by plooshi** [comment]
@P5-2005 usbdkhelper.dll is also opensource, https://github.com/daynix/UsbDk/tree/master/UsbDkHelper

**Comment by P5-2005** [comment]
> @P5-2005 yes, but linux also patches forever... so im guessing thats a different issue

if you see checkra1n on linux with A7 is same issue, because of libusb xD

**Comment by plooshi** [comment]
> > @P5-2005 yes, but linux also patches forever... so im guessing thats a different issue
> 
> if you see checkra1n on linux with A7 is same issue, because of libusb xD

i know

**Comment by amats211** [comment]
> @P5-2005 yes, but linux also patches forever... so im guessing thats a different issue

Have experienced it before..

https://github.com/0x7ff/gaster/issues/22

i think the output from kmsg has same usb descriptor error..

4,1064,190137372,-;usb 1-1: config index 0 descriptor too short (expected 25, got 9)
SUBSYSTEM=usb
DEVICE=+usb:1-1
4,1065,190137384,-;usb 1-1: config 1 has 0 interfaces, different from the descriptor's value: 1

**Comment by plooshi** [comment]
@amats211 i meant like won't stop patching... seems like somehow it's not able to patch correctly on these devices...

**Comment by amats211** [comment]
> @amats211 i meant like won't stop patching... seems like somehow it's not able to patch correctly on these devices...

oh that problem, you just need to put the libusb-1.0.dll in the folder where gaster.exe is before you run it

**Comment by ploosh-alt** [comment]
> oh that problem, you just need to put the libusb-1.0.dll in the folder where gaster.exe is before you run it

@amats211 what about on linux? im on A7 (8960)
