### ISSUE TITLE
A10X gets stuck on checkm8

### ISSUE THREAD

**Issue by verygenericname** [0x7ff/gaster#31]

**Comment by verygenericname** [comment]
as in it loops, i'm not sure where it gets stuck on, but I don't have a A10X device. but all the other people who try this gets stuck in a loop

**Comment by alfiecg24** [comment]
I can second this, wondering if it's exclusive to M1 Macs and their known issues with checkm8? Maybe using manual reset option could help?

**Comment by alfiecg24** [comment]
Manual reset didn't help, but using an earlier commit worked for now

**Comment by 0x7ff** [comment]
Please try the latest commit. I increased usb_timeout, removed enter_critical_section and exit_critical_section as ipwndfu also does this.

**Comment by verygenericname** [comment]
ok

**Comment by alfiecg24** [comment]
Doesn't seem to work for me

**Comment by alfiecg24** [comment]
Using the other commits from September 21st and October 5th result in `[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227` indefinitely after the PATCH stage - which is a different result to the looping

**Comment by alfiecg24** [comment]
It looks like 12th September is the last working commit for A10X

**Comment by 0x7ff** [comment]
Please replace "3 * EP0_MAX_PACKET_SZ + 1" with "DFU_MAX_TRANSFER_SZ" at https://github.com/0x7ff/gaster/blob/main/gaster.c#L1481 then tell me the result.

**Comment by alfiecg24** [comment]
Works perfectly, thanks. Is this exclusive to T8011 or will the change be implemented for all devices?

**Comment by alfiecg24** [comment]
I submitted a pull request with a fix if that is all that is needed

**Comment by 0x7ff** [comment]
Thanks @alfiecg24 @verygenericname
