### ISSUE TITLE
no payload_A9.h

### ISSUE THREAD

**Issue by waqaw** [0x7ff/gaster#34]
![image](https://user-images.githubusercontent.com/50660666/196382676-f1e91440-6db7-45ed-80fe-307e41315d66.jpg)

**Comment by plooshi** [comment]
Use make libusb.

**Comment by waqaw** [comment]
Can you teach me how to use it?

**Comment by plooshi** [comment]
make libusb

**Comment by plooshi** [comment]
its a command

**Comment by ICH525** [comment]
comment #44 usefull
