### ISSUE TITLE
iPadOS 15.3.1 fail to pwn

### ISSUE THREAD

**Issue by demhademha** [0x7ff/gaster#36]
CPID: 0x8010
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8010
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

**Comment by ploosh-alt** [comment]
what does the device do when it fails

**Comment by demhademha** [comment]
The device boots  to normal mode however occasionally it enters recovery

**Comment by Tokarak** [comment]
Same as #38
