### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by V1c1v** [0x7ff/gaster#41]
Hi sory to disturb ,How to fix this error during make?
xxd -iC payload_A9.bin payload_A9.h
process_begin: CreateProcess(NULL, xxd -iC payload_A9.bin payload_A9.h, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [macos] Error 2

thanks ,

**Comment by Moneymoney122** [comment]
What Operating System?

**Comment by V1c1v** [comment]
Windows 10

**Comment by Moneymoney122** [comment]
Did you run “make libusb” and not “make”?

**Comment by V1c1v** [comment]
I run make Makefile

**Comment by V1c1v** [comment]
here screenahot of my command
![make](https://user-images.githubusercontent.com/94830625/202181730-f2c61031-146b-402c-994d-206379ef233c.jpg)

**Comment by Moneymoney122** [comment]
run "make libusb" while in the gaster directory

**Comment by V1c1v** [comment]
make: C:\Users\user\Desktop\gaster\gaster-main\libusb: No such file or directory
make: *** No rule to make target 'C:\Users\user\Desktop\gaster\gaster-main\libusb'.  Stop.

**Comment by ICH525** [comment]
$ make libusb
xxd -iC payload_A9.bin payload_A9.h
make: xxd: No such file or directory
make: *** [Makefile:15: libusb] Error 127

**Comment by ICH525** [comment]
comment #44 usefull

**Comment by Tokarak** [comment]
Maybe its time to stick this in a readme?
