### ISSUE TITLE
gaster decrypt exits 1 on A9 (failed to decrypt iBSS)

### ISSUE THREAD

**Issue by PoomSmart** [0x7ff/gaster#47]
Simplified command (run during jailbreaking with palera1n):

`gaster decrypt iBSS.n69u.RELEASE.im4p iBSS.dec`

Output:

```
usb_timeout: 5
usb_abort_timeout_min: 0
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8000
Found the USB handle.
Now you can boot untrusted images.
[IOKit] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
Found the USB handle.
```

Environment: macOS Ventura 13.2 (22D49)
Device: iPhone SE 1st generation (N69u) iOS 15.1

**Comment by PoomSmart** [comment]
Turns out manually entering DFU mode (shutting down the device, booting then entering DFU) did the trick. It could be that DFU mode that is entered during recovery mode as prepared by palera1n script won't work.

**Comment by dualra1n** [comment]
> Turns out manually entering DFU mode (shutting down the device, booting then entering DFU) did the trick. It could be that DFU mode that is entered during recovery mode as prepared by palera1n script won't work.

did this work for you, sir?
