### ISSUE TITLE
Hanging after patch stage

### ISSUE THREAD

**Issue by AverageUser231** [0x7ff/gaster#50]
I am doing this on an iPhone 5s on Manjaro and it always just hangs after the patch stage and no matter how long I leave it for it just doesn't do anything after it

Logs:

[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: RESET
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SETUP
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: SPRAY
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227
CPID: 0x8960
Found the USB handle.
Stage: PATCH
ret: true
[libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

**Comment by LuckyHeroes** [comment]
> I am doing this on an iPhone 5s on Manjaro and it always just hangs after the patch stage and no matter how long I leave it for it just doesn't do anything after it
> 
> Logs:
> 
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: SETUP ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: SPRAY ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

Are you using AMD CPU / Motherboard. If so your usb controller is incompatible. You need a PCI usb hub and do the usb trick

**Comment by LuckyHeroes** [comment]
> I am doing this on an iPhone 5s on Manjaro and it always just hangs after the patch stage and no matter how long I leave it for it just doesn't do anything after it
> 
> Logs:
> 
> [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: RESET ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: SETUP ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: SPRAY ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227 CPID: 0x8960 Found the USB handle. Stage: PATCH ret: true [libusb] Waiting for the USB handle with VID: 0x5AC, PID: 0x1227

Also if gaster doesn’t fully complete the PWN your iPhone usb controller can become unresponsive. The only solution I’ve found that fixes that’s is a complete Erase/Restore Via iTunes (letting your battery fully drain to 0% may also fix that issue)

**Comment by plooshi** [comment]
my fix for this was to unplug and replug the device after 5 or 6 seconds of it hanging

**Comment by AverageUser231** [comment]
> my fix for this was to unplug and replug the device after 5 or 6 seconds of it hanging

Thanks, it worked!
