### ISSUE TITLE
Boot Pwnd mode success, send ramdisk done, but i can't connect SSH at A9, A10 devices

### ISSUE THREAD

**Issue by mon0208** [0x7ff/gaster#6]
I tested after Boot Pwnd mode success, send ramdisk done, i can connect ssh on A11 devices, but on A9, A10 i can't connect SSH. Pls help me!

**Comment by 0x7ff** [comment]
If it's also same for rmsigchks.py, possibly a restored_external issue.

**Comment by mon0208** [comment]
i tryed with gaster today not work

**Comment by CDSQ** [comment]
too

**Comment by P5-2005** [comment]
A10-A11 A8 no issue from my end, i dont have A9 to test this
