### ISSUE TITLE
Can’t boot ibss/ibec on T2 devices, stays in dfu

### ISSUE THREAD

**Issue by ak99004242** [0x7ff/gaster#8]
when u boot ibss or ibec on T2 MacBooks it stays in dfu and doesn’t go in recovery

**Comment by P5-2005** [comment]
worked for me no issue, depend which ibss/ibec brideos used and which patcher like kairos

**Comment by ak99004242** [comment]
> worked for me no issue, depend which ibss/ibec brideos used and which patcher like kairos

Are you using irecovery to send img4 format? I m using the earliest bridge os 4.2. I did patch it with kairos and signed as well with fake im4m

**Comment by P5-2005** [comment]
yes, irecovery, kairos but not last version, and bridgeos 5.1, all fine

**Comment by ak99004242** [comment]
> 

I have tried 5.1 but it stays in dfu doesn’t go in recovery at all. Will u be able to check or can You check my files if I upload them?

**Comment by ak99004242** [comment]
> 

If I use pwndfu and remove signature checks I can send raw ibss and it works but with gaster it doesn’t. I have tried few different ibss and ibec
